### ISSUE TITLE
Error: Could not find or load main class SpeechRecognitionAI.jar

### ISSUE THREAD

**Issue by Dionisgr** [viktorvano/SpeechRecognitionAI#20]
It is very interesting, but unfortunately, when running in Debian, it gives an error.
Error: Could not find or load main class SpeechRecognitionAI.jar
Caused by: java.lang.ClassNotFoundException: SpeechRecognitionAI.jar

**Comment by viktorvano** [comment]
I am personally running it on Ubuntu Desktop 20.04.
I use JavaFX SDK 18 and also have installed Java SDK (maybe 17).
It should with Java 8 alone, because that one has also JavaFX in itself.
Let me know if this script will work for you.

I have a sh script with relative paths and loaded modules like this (but absolute paths will work too):
parent_path=$( cd "$(dirname "${BASH_SOURCE[0]}")" ; pwd -P )
sudo java --module-path /home/viktorvano/JavaApps/javafx/javafx-sdk-18.0.1/lib --add-modules=javafx.controls,javafx.fxml,javafx.base,javafx.media,javafx.web,javafx.swing -jar $parent_path/SpeechRecognitionAI.jar

**Comment by Dionisgr** [comment]
Thanks everything started. And could you add instructions for integration with a Home assistant.

**Comment by viktorvano** [comment]
I just trigger automations with that.
https://raw.githubusercontent.com/viktorvano/SpeechRecognitionAI/master/Document%20Files/Webhooks.png
So create an automation and create a webhook url as a trigger.

**Comment by Dionisgr** [comment]
Then there was another question. The program has only "IP mic" at the moment, it is impossible for me to purchase the application. Is it impossible to use a local microphone with this program? (Or have I not figured it out yet?)

**Comment by viktorvano** [comment]
The **local hardware microphone can be used** on your device. You just need to uncheck "IP Mic" in options.
And it starts recording and stops automatically depending on your mic sensitivity and configuration of word detection algorithm parameters.
